{
 "title": "Dashboard de Votacao",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Votos por Minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(votos_total[1m]) * 60" }
   ]
  },
  {
   "title": "Tempo Medio de Resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(tempo_resposta_segundos_sum[1m]) / rate(tempo_resposta_segundos_count[1m])"
    }
   ]
  },
  {
   "title": "Taxa de Erros",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(erros_total[1m])" }
   ]
  },
  {
   "title": "Taxa de Sucesso",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (rate(erros_total[1m]) / rate(votos_total[1m]) * 100)"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100"
    }
   ]
  },
  {
   "title": "Uso de Memoria",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Requisicoes por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(requisicoes_total[1m])" }
   ]
  },
  {
   "title": "Requisicoes em Andamento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "fastapi_inprogress" }
   ]
  },
  {
   "title": "Total de Votos por Participante",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "votos_redis" }
   ]
  },
  {
   "title": "Votos por Hora ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(votos_por_hora[1h])" }
   ]
  }
 ]
}